/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package strings;

import org.junit.Test;
import palindrome.PalindromeChecker;
import static org.junit.Assert.*;

public class PalindromeTest {
    @Test public void emptyStringShouldBeAPalindrome() {
        assertTrue("Expected empty string to be a palindrome", PalindromeChecker.isPalindrome(""));
    }
    @Test public void charOneShouldBePalindrome(){
        assertTrue("Expected char one to be a palindrome",PalindromeChecker.isPalindrome("A"));
    }
    @Test public void stringDifferentCharShouldNotBePalindrome(){
        assertFalse("Expected String different char not  to be a palindrome",PalindromeChecker.isPalindrome("java"));
    }
    @Test public void stringViceaVercaSholudBePalindrome(){
        assertTrue("Expected String with vice a versa Sholud be Palindrome",PalindromeChecker.isPalindrome("nittin"));
    }
}
